#!/usr/bin/env ruby
# frozen_string_literal: true

require "isola"
require "thor"
require "listen"

class IsolaCLI < Thor
  package_name "Isola"

  desc "build site", "build site on current directory"
  def build
    site = construct_site
    site.build
  end

  desc "serve", "build site and serve"
  def serve
    site = construct_site
    site.build

    site_dir = File.join(site.root_dir, site.config[:destination])
    host = site.config[:host]
    port = site.config[:port]
    server = Isola::DevServer.new(site_dir, host, port)

    watcher = Isola::Watcher.new(site) { server.notify_reload }
    listener = Listen.to(File.expand_path(site.root_dir), &watcher.method(:handle_changes))
    listener.start

    puts "serving at http://#{host}:#{port}"
    server.start
  end

  private

  def construct_site
    config =
      if File.exist? "_config.yaml"
        File.read("_config.yaml")
      else
        ""
      end
    Isola::Site.new(config)
  end
end

IsolaCLI.start(ARGV)
