name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    name: test
    strategy:
      matrix:
        ruby: [3.4, 4.0, jruby, truffleruby]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - ruby: truffleruby
            platform: windows-latest
          - ruby: jruby
            platform: windows-latest
    runs-on: ${{ matrix.platform }}            
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
  ci:
    if: ${{ always() }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: All tests passed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
